apiVersion: apps/v1
kind: Deployment
metadata:
  name: fakewebserver  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fakewebserver
  template:
    metadata:
      labels:
        app: fakewebserver
    spec:
      containers:

      - name: fakewebserver
        image: zanatabr/fakewebserver

        ports: 
        - name: http
          containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: fakewebserver-service
spec:
  selector: 
    app: fakewebserver
  type: LoadBalancer
  ports:
  - name: http
    port: 8000
